version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: smart_home_mongodb_dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: smart_home_password
      MONGO_INITDB_DATABASE: smart_home_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - smart_home_network_dev

  # Redis for development
  redis:
    image: redis:7-alpine
    container_name: smart_home_redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - smart_home_network_dev
    command: redis-server --appendonly yes

volumes:
  mongodb_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  smart_home_network_dev:
    driver: bridge
